### ISSUE TITLE
Error during marking episodes as watched

### ISSUE THREAD

**Issue by DavidClapp23** [imrabti/tvshowtime-plex#29]
I am running PMS on a Windows Server 2012R2.
I followed your instructions to grab the X-Plex-Token put that in the properties files.
Then ran the jar and got my code, logged into TVShowtime and put the code in and then I got an error and I keep getting the same error every time I execute the jar:
18:21 INFO  - Starting ApplicationLauncher v1.0.5-RELEASE on Paranor with PID 6516 (D:\Program Files\tvshowtime-plex\tvshowtimeplex.jar started by Administrator in C:\Users\Administrator)
18:21 INFO  - No active profile set, falling back to default profiles: default
18:21 INFO  - Started ApplicationLauncher in 1.672 seconds (JVM running for 2.017)
18:21 INFO  - AccessToken loaded from file with success : AccessToken{access_token='removedthis'}
18:21 ERROR - Error during marking episodes as watched.
18:21 ERROR - 401 Unauthorized

Any thoughts on why I might be getting a 401?

**Comment by imrabti** [comment]
Hello, this was already resolved in  #25

**Comment by DavidClapp23** [comment]
My apologies, yes I should have dug deeper into comments.
