### ISSUE TITLE
Constant "Waiting for you to type in the code in TVShowTime"

### ISSUE THREAD

**Issue by Glynnryan** [imrabti/tvshowtime-plex#31]
Is it necessary to constantly type the verification code to authorise the app everytime I want to sync Plex with TVST using this script?

Latst script log:
 _____     _____ _                 _____ _                      ______ _
|_   _|   /  ___| |               |_   _(_)                     | ___ \ |
  | |_   _\ `--.| |__   _____      _| |  _ _ __ ___   ___ ______| |_/ / | _____  __
  | \ \ / /`--. \ '_ \ / _ \ \ /\ / / | | | '_ ` _ \ / _ \______|  __/| |/ _ \ \/ /
  | |\ V //\__/ / | | | (_) \ V  V /| | | | | | | | |  __/      | |   | |  __/>  <
  \_/ \_/ \____/|_| |_|\___/ \_/\_/ \_/ |_|_| |_| |_|\___|      \_|   |_|\___/_/\_\

   :::  TVShowTime-Plex (V1.0.5)  :::

11:39 INFO  - Starting ApplicationLauncher v1.0.5-RELEASE on Glynn-PC with PID 13468 (F:\tmp\tvshowtime-plex-1.0.5\tvshowtimeplex.jar started by Glynn in C:\)
11:39 INFO  - No active profile set, falling back to default profiles: default
11:39 INFO  - Started ApplicationLauncher in 3.77 seconds (JVM running for 4.663)
11:39 INFO  - Linking with your TVShowTime account using the code C5T-hn2-3Oc-FAlRXgcK
11:39 INFO  - Please open the URL https://www.tvshowtime.com/activate in your browser
11:39 INFO  - Connect with your TVShowTime account and type in the following code :
11:39 INFO  - d5c6-c08a
11:39 INFO  - Waiting for you to type in the code in TVShowTime :-D ...
Exception in thread "Timer-0" org.springframework.web.client.HttpClientErrorException: 403 Forbidden
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498)
        at org.nuvola.tvshowtime.ApplicationLauncher.loadAccessToken(ApplicationLauncher.java:166)
        at org.nuvola.tvshowtime.ApplicationLauncher.access$000(ApplicationLauncher.java:64)
        at org.nuvola.tvshowtime.ApplicationLauncher$1.run(ApplicationLauncher.java:137)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)

**Comment by imrabti** [comment]
No it is not necessary, the token is stored inside a file so that you don't have to type that every time. 

In you case I think the file that stores the token is deleted or not found. You can fix that by specifying the path where of the file that contain the token (it is better to give an absolute path, rather than a relative one).

You can do that by overriding the value of the property **nuvola.tvshowtime.tokenFile** located in the file **application.properties** inside the **config** folder.

**Comment by Glynnryan** [comment]
Hi Imrabti, thanks for getting back to me.
I have tried overriding the property as suggested, see my config below. However I still get prompted to constantly enter the verification code and link TVST to the script. Please help??

Config as follows:
REQUIRED: nuvola.pms.path is the location of the http service exposed by Plex Media Server the default value should be 'ok', assuming you're running the tvshowtime-plex on the same machine where the PMS is installed
nuvola.pms.path = http://192.168.1.3:32400

REQUIRED: starting from Plex media server 1.1 a **token** is required, PMS secure all web services calls. To find the 'X-Plex-Token' follow this article : http://bit.ly/1PqlB1v
nuvola.pms.token = [hidden]

REQUIRED: Where do you wish to write the token used for authorizing access to you TVShow Time account, the default value should be 'ok'
nuvola.tvshowtime.tokenFile = F:\tmp\TVShowTimePlex

REQUIRED: Where do you wish to write the tvshowtime-plex log file.
logging.path = F:\tmp\TVShowTimePlex
logging.pattern.console=%d{HH:mm} %-5level - %msg%n
logging.level.root = ERROR
logging.level.org.nuvola.tvshowtime = INFO

**Comment by imrabti** [comment]
**nuvola.tvshowtime.tokenFile = F:\tmp\TVShowTimePlex** You store the token in a temporary (tmp) folder which get deleted and you loose the token and that's why next time it will ask you again.
Try to store it in a permanent place so it doesn't get deleted.

**Comment by Glynnryan** [comment]
The "tmp" folder was a folder I had made for the script. I renamed the folder and changed the config to correct the file paths, but am still getting the same issue.... Am I being retarded?

New config:
REQUIRED: nuvola.pms.path is the location of the http service exposed by Plex Media Server
the default value should be 'ok', assuming you're running the tvshowtime-plex on the same machine
where the PMS is installed
nuvola.pms.path = http://192.168.1.3:32400

REQUIRED: starting from Plex media server 1.1 a **token** is required, PMS secure all web services calls.
To find the 'X-Plex-Token' follow this article : http://bit.ly/1PqlB1v
nuvola.pms.token = [hidden]

REQUIRED: Where do you wish to write the token used for authorizing access to
you TVShow Time account, the default value should be 'ok'
nuvola.tvshowtime.tokenFile = F:\TVShowTimePlex\Token

REQUIRED: Where do you wish to write the tvshowtime-plex log file.
logging.path = F:\TVShowTimePlex\Logs
logging.pattern.console=%d{HH:mm} %-5level - %msg%n
logging.level.root = ERROR
logging.level.org.nuvola.tvshowtime = INFO

**Comment by Glynnryan** [comment]
... Any chance of getting some help with this please @imrabti ?

> The "tmp" folder was a folder I had made for the script. I renamed the folder and changed the config to correct the file paths, but am still getting the same issue.... Am I being retarded?

> New config:

> REQUIRED: nuvola.pms.path is the location of the http service exposed by Plex Media Server
the default value should be 'ok', assuming you're running the tvshowtime-plex on the same machine
where the PMS is installed
> nuvola.pms.path = http://192.168.1.3:32400

> REQUIRED: starting from Plex media server 1.1 a token is required, PMS secure all web services calls.
> To find the 'X-Plex-Token' follow this article : http://bit.ly/1PqlB1v
> nuvola.pms.token = [hidden]

> REQUIRED: Where do you wish to write the token used for authorizing access to you TVShow Time account, the default value should be 'ok'
> nuvola.tvshowtime.tokenFile = F:\TVShowTimePlex\Token

> REQUIRED: Where do you wish to write the tvshowtime-plex log file.
> logging.path = F:\TVShowTimePlex\Logs
> logging.pattern.console=%d{HH:mm} %-5level - %msg%n
> logging.level.root = ERROR
> logging.level.org.nuvola.tvshowtime = INFO

**Comment by fletch8527** [comment]
@Glynnryan I just set it up on my server and had the same issue. I was able to get it working once but as soon as I tried it as a scheduled task it kept asking to verify with TVShowTime. My issue was that I need to specify the scheduled task to 'start it' the directory where the session token was. My scheduled task action is:
Action: Start a program
Settings
Program/script: java
Add arguments: -jar M:\tvshowtime-plex-1.0.5\tvshowtimeplex.jar
Start in: M:\tvshowtime-plex-1.0.5

EDIT: it looks like my initial issue was with the session token path being relative, but I see that yours is absolute... does your 'Token' file exist in F:\TVShowTimePlex?

**Comment by Glynnryan** [comment]
I'm not too worried about the task scheduler at this stage... Just trying to get the script to run. I've noticed the following in the on-screen logs during the running of the script:

Edit: I've removed the part of my previous comment as i managed to tinker with the scrip code and got the script running. The problem is that the log states "All episodes are processed successfully ..." but checking my TVST profile doesn't show the same watched/unwatched episodes.

@imrabti @mikefletcher85, any suggestions?

**Comment by fletch8527** [comment]
@glynnryan unfortunately I don't know anything on how the script works. I had the same issue you did (401 unauthorized) but I see you got that fixed. I havnt had much of a chance to test yet as I was diligent manually marking shows as watched in TVST. I'll try it out over the next week and report back in there is issues.

**Comment by imrabti** [comment]
Sorry @Glynnryan  and @mikefletcher85 I have been busy these days, I'll look into the issue you have today and try to solve that. Maybe the service stopped working with the new version of Plex or some changes in TVShowTime API.

**Comment by fletch8527** [comment]
@imrabti I just checked this morning and it appears to be working correctly for me. Thank you very much for this. It was always a pain to have to update TVST manually.

**Comment by Glynnryan** [comment]
Everything seems to be working @mikefletcher85 & @imrabti ... I will be scheduling a task to run daily. 

Thanks again for the help to both of you!
