### ISSUE TITLE
 401 Unauthorized

### ISSUE THREAD

**Issue by Glynnryan** [imrabti/tvshowtime-plex#32]
Since this past weekend I have been getting a " 401 Unauthorized" when trying to sync my watched shows.
Any idea what may be causing this? I have removed my token file re-authorised the API, but am still getting the same issue.

Here is a log from my last sync attempt where I deleted the token file and tried to run the script:
08:15 INFO  - Starting ApplicationLauncher v1.0.5-RELEASE on Glynn-PC with PID Glynn-PC with PID 10084 (C:\TVShowTimePlex\tvshowtime-plex-1.0.5\tvshowtimeplex.jar started by Glynn in C:\TVShowTimePlex\tvshowtime-plex-1.0.5)
08:15 INFO  - No active profile set, falling back to default profiles: default
08:15 INFO  - Started ApplicationLauncher in 5.061 seconds (JVM running for 6.037)
08:15 INFO  - Linking with your TVShowTime account using the code xxxxxxxxxxxxxxxxxxxx
08:15 INFO  - Please open the URL https://www.tvshowtime.com/activate in your browser
08:15 INFO  - Connect with your TVShowTime account and type in the following code :
08:15 INFO  - xxxxxxxxxxxx
08:15 INFO  - Waiting for you to type in the code in TVShowTime :-D ...
08:16 INFO  - AccessToken from TVShowTime with success : AccessToken{access_token='xxxxxxxxxxxxxxxx'}
08:16 INFO  - AccessToken store successfully inside a file...
08:16 INFO  - Calling Plex with a X-Plex-Token...
Exception in thread "Timer-0" org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:312)
        at org.nuvola.tvshowtime.ApplicationLauncher.processWatchedEpisodes(ApplicationLauncher.java:214)
        at org.nuvola.tvshowtime.ApplicationLauncher.loadAccessToken(ApplicationLauncher.java:175)
        at org.nuvola.tvshowtime.ApplicationLauncher.access$000(ApplicationLauncher.java:64)
        at org.nuvola.tvshowtime.ApplicationLauncher$1.run(ApplicationLauncher.java:137)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)

Here is a log when I try run the script immediately after with the token file just created:
08:18 INFO  - Starting ApplicationLauncher v1.0.5-RELEASE on Glynn-PC with PID 4108 (C:\TVShowTimePlex\tvshowtime-plex-1.0.5\tvshowtimeplex.jar started by Glynn in C:\TVShowTimePlex\tvshowtime-plex-1.0.5)
08:18 INFO  - No active profile set, falling back to default profiles: default
08:18 INFO  - Started ApplicationLauncher in 4.306 seconds (JVM running for 5.309)
08:18 INFO  - AccessToken loaded from file with success : AccessToken{access_token='xxxxxxxxxxxxxx'}
08:18 INFO  - Calling Plex with a X-Plex-Token...
08:18 ERROR - Error during marking episodes as watched.
08:18 ERROR - 401 Unauthorized

Access token's and access codes have been changed to "xxxxxxxx."

Any suggestions?
Thanks in advance.
G

**Comment by Greg285** [comment]
Hi,

I have something similar with the scrobbler - runnin on a ds1515+ synology.
Were you able to fix this ?

@imrabti : is it possible for you to have a look on this issue ?

Thanks

**Comment by imrabti** [comment]
Hello, sorry for the late answer I'll take a look on the issue this weekend.

**Comment by Glynnryan** [comment]
Great, thank you

**Comment by imrabti** [comment]
@Glynnryan @Greg285 It appears that you are getting this error because you didn't provide Plex-Token. This is explained on the ReadMe you need to get the Plex token as explained in here http://bit.ly/1PqlB1v and put that value in the field **nuvola.pms.token**  of the configuration file application.properties located in the config folder.

**Comment by Glynnryan** [comment]
@imrabti I did have a Plex token specified, but somehow the token changed. After looking up the Plex Token and updating my config file with the toke, the sync is working again.

Do you know if the Plex token changes on its own from time to time?

**Comment by imrabti** [comment]
Usually it shouldn't change, maybe there was a major update to Plex Media Server and they regenerate it for everyone.

If you have PlexPass subscription I'm currently working on new version of the plugin that will not require Plex Token.

**Comment by Greg285** [comment]
Hi,

Thanks for pointing this out :)
I also did enter the plex token but for unknow reason it changes and was not saved in the config file 

Now all is fine ^^

_19:43 INFO  - AccessToken store successfully inside a file...
19:43 INFO  - Calling Plex with a X-Plex-Token...
19:43 INFO  - All episodes are processed successfully ..._

@imrabti : stupid question, is it automatically updating the tvshowtime db ? or do we have to schedule the java command in a crontab ?

_edit : mark automatically episodes in your TVShowTime account as soon as you did watch them in your Plex system.__

So its supposed to update it automatically apparently

edit : 
so looks like the webpage is updated but not the android app....am i missing something ?
Do we need to wait for the app to be refreshed ?
