### ISSUE TITLE
Doubts to upgrade auto

### ISSUE THREAD

**Issue by rb0rges** [imrabti/tvshowtime-plex#40]
Hello!
Firstly thanks for this development, because the official is very difficult to install if it is windows, I really could not.

My question is simple, to update my TV Time, will I always have to run the .jar file manually or can I do this automatically?

So I always update as soon as I watch an episode!

**Comment by vampywiz17** [comment]
if you use Windows: https://www.digitalcitizen.life/how-create-task-basic-task-wizard

if you use Linux: http://kvz.io/blog/2007/07/29/schedule-tasks-on-linux-using-crontab/

**Comment by rb0rges** [comment]
Okay, I'll test that.
New doubt, configuring the scheduler, shortly after the execution of .jar will it be scheduled to close alone?

**Comment by vampywiz17** [comment]
Windows or Linux?

On linux, i use this:

```
0 * * * * java -jar /home/vamp/tvshowtimeplex/tvshowtime-plex-1.0.6/tvshowtimeplex.jar

10 * * * * pkill -f 'java -jar'

```

It run every hour and after every hour + 10 min close all java applet.

On windows, you able to use 'Taskkill' command:

`taskkill /f /im "appname"
`

https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/closing-a-program-using-task-scheduler/bb322594-6965-4657-bc2f-4b95ceba46ec?auth=1

**Comment by rb0rges** [comment]
Thank you
