### ISSUE TITLE
Issue OAuth

### ISSUE THREAD

**Issue by ouklu** [imrabti/tvshowtime-plex#45]
Hello,

Quick question, how do I force it give me a code to authentificate in tvshowtime?

For the moment I just get the following:

|_   _|   /  ___| |               |_   _(_)                     | ___ \ |
  | |_   _\ `--.| |__   _____      _| |  _ _ __ ___   ___ ______| |_/ / | _____  __
  | \ \ / /`--. \ '_ \ / _ \ \ /\ / / | | | '_ ` _ \ / _ \______|  __/| |/ _ \ \/ /
  | |\ V //\__/ / | | | (_) \ V  V /| | | | | | | | |  __/      | |   | |  __/>  <
  \_/ \_/ \____/|_| |_|\___/ \_/\_/ \_/ |_|_| |_| |_|\___|      \_|   |_|\___/_/\_\

   :::  TVShowTime-Plex (V1.0.5)  :::

13:31 INFO  - Starting ApplicationLauncher v1.0.5-RELEASE on plex-plexpass with PID 65622 (/mnt/tvshowtime-plex-1.0.5/tvshowtimeplex.jar started by root in /mnt/tvshowtime-plex-1.0.5)
13:31 INFO  - No active profile set, falling back to default profiles: default
13:32 INFO  - Started ApplicationLauncher in 5.033 seconds (JVM running for 6.218)
13:32 ERROR - OAuth authentication TVShowTime failed.
13:32 ERROR - I/O error on POST request for "https://api.tvshowtime.com/v1/oauth/device/code": sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

**Comment by djscudo** [comment]
URL api.tvshowtime.com was changed to api.tvtime.com the certificate for the old one was expired few weeks ago.
To solve this issue you should change that URL

**Comment by ouklu** [comment]
perfect thanks, next question will be, where is the api configured? Cause I greped but can't seem to find it 
sorry, bit of a noob when it comes to java

**Comment by djscudo** [comment]
The url is in Constants.java
It will be updated with PR [#46](https://github.com/imrabti/tvshowtime-plex/pull/46 )

**Comment by ouklu** [comment]
ok perfect thanks a lot
